### ISSUE TITLE
postInstallation script fails on centOS 7 

### ISSUE THREAD

**Issue by reschandreas** [bitnami/bitnami-docker-moodle#106]
**Description**

**Steps to reproduce the issue:**

1. clone the given docker-compose.yml
2. run`docker-compose up -d`
3. observe the log

**Describe the results you received:**

I'm getting this log:

```
Welcome to the Bitnami moodle container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-moodle
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-moodle/issues

WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
nami    INFO  Initializing apache
nami    INFO  apache successfully initialized
nami    INFO  Initializing php
nami    INFO  php successfully initialized
nami    INFO  Initializing mysql-client
nami    INFO  mysql-client successfully initialized
nami    INFO  Initializing moodle
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at mariadb:3306
mysql-c INFO  MySQL server listening and working at mariadb:3306
moodle  INFO  Running Moodle install. Please be patient...
Error executing 'postInstallation': EEXIST: file already exists, symlink '/bitnami/moodle' -> '/opt/bitnami/moodle'
```

I tested the docker-compose on my private laptop running macOS and it worked just fine.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:25 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:25 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

- Output of `docker info`:

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 30
Server Version: 17.05.0-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-1062.4.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.603GiB
Name: magma19.interhyp-linuxdmz.de
ID: 65BA:3ZHD:MVXK:HF2N:6OBM:L446:DQWV:IZ7Y:GW3E:5HVK:PHKZ:HITW
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 docker-public.interhyp-intern.de:443
 127.0.0.0/8
Live Restore Enabled: false

WARNING: overlay: the backing xfs filesystem is formatted without d_type support, which leads to incorrect behavior.
         Reformat the filesystem with ftype=1 to enable d_type support.
         Running without d_type support will not be supported in future releases.
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

- Output of `docker-compose version` (if applicable):
```
docker-compose version 1.24.1, build 4667896b
docker-py version: 3.7.3
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018
```
**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
My machine is a Virtual Machine running CentOS 7

**Comment by sameersbn** [comment]
@reschandreas a similar issue was reported before in https://github.com/bitnami/bitnami-docker-phabricator/issues/105#issuecomment-412953665 and the it turned out that the user had to upgrade their docker version. Could you please try the same and report back while we try to reproduce this issue?

**Comment by reschandreas** [comment]
I just upgraded everything.

Output of `docker version`

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:25:41 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:24:18 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

Output of `docker info`

```
Client:
 Debug Mode: false

Server:
 Containers: 2
  Running: 1
  Paused: 0
  Stopped: 1
 Images: 50
 Server Version: 19.03.5
 Storage Driver: overlay
  Backing Filesystem: xfs
  Supports d_type: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-1062.7.1.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 7.603GiB
 Name: magma19.interhyp-linuxdmz.de
 ID: 65BA:3ZHD:MVXK:HF2N:6OBM:L446:DQWV:IZ7Y:GW3E:5HVK:PHKZ:HITW
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  docker-public.interhyp-intern.de:443
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
WARNING: the overlay storage-driver is deprecated, and will be removed in a future release.
WARNING: overlay: the backing xfs filesystem is formatted without d_type support, which leads to incorrect behavior.
         Reformat the filesystem with ftype=1 to enable d_type support.
         Running without d_type support will not be supported in future releases.

```
Output of `docker-compose version`

```
docker-compose version 1.25.0, build 0a186604
docker-py version: 4.1.0
CPython version: 3.7.4
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

But I still get the following logs:

Log of `mariadb`
```
 12:44:18.51 
 12:44:18.51 Welcome to the Bitnami mariadb container
 12:44:18.51 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
 12:44:18.51 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
 12:44:18.51 Send us your feedback at containers@bitnami.com
 12:44:18.52 
 12:44:18.52 INFO  ==> ** Starting MariaDB setup **
 12:44:18.63 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
 12:44:18.63 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
 12:44:18.63 INFO  ==> Initializing mariadb database
 12:44:18.65 INFO  ==> Installing database
 12:44:21.59 INFO  ==> Starting mariadb in background
 12:44:22.65 INFO  ==> Configuring authentication
 12:44:22.95 INFO  ==> Running mysql_upgrade
 12:44:23.95 INFO  ==> Stopping mariadb
 12:44:25.97 INFO  ==> ** MariaDB setup finished! **

 12:44:26.10 INFO  ==> ** Starting MariaDB **
2019-12-06 12:44:26 0 [Note] /opt/bitnami/mariadb/sbin/mysqld (mysqld 10.3.20-MariaDB) starting as process 1 ...
2019-12-06 12:44:26 0 [Note] InnoDB: Using Linux native AIO
2019-12-06 12:44:26 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2019-12-06 12:44:26 0 [Note] InnoDB: Uses event mutexes
2019-12-06 12:44:26 0 [Note] InnoDB: Compressed tables use zlib 1.2.8
2019-12-06 12:44:26 0 [Note] InnoDB: Number of pools: 1
2019-12-06 12:44:26 0 [Note] InnoDB: Using SSE2 crc32 instructions
2019-12-06 12:44:26 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
2019-12-06 12:44:26 0 [Note] InnoDB: Completed initialization of buffer pool
2019-12-06 12:44:26 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
2019-12-06 12:44:26 0 [Note] InnoDB: 128 out of 128 rollback segments are active.
2019-12-06 12:44:26 0 [Note] InnoDB: Creating shared tablespace for temporary tables
2019-12-06 12:44:26 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2019-12-06 12:44:26 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
2019-12-06 12:44:26 0 [Note] InnoDB: Waiting for purge to start
2019-12-06 12:44:26 0 [Note] InnoDB: 10.3.20 started; log sequence number 1630824; transaction id 21
2019-12-06 12:44:26 0 [Note] InnoDB: Loading buffer pool(s) from /bitnami/mariadb/data/ib_buffer_pool
2019-12-06 12:44:26 0 [Note] InnoDB: Buffer pool(s) load completed at 191206 12:44:26
2019-12-06 12:44:26 0 [Note] Plugin 'FEEDBACK' is disabled.
2019-12-06 12:44:26 0 [Note] Server socket created on IP: '0.0.0.0'.
2019-12-06 12:44:26 0 [Warning] 'proxies_priv' entry '@% root@1526c1b1886f' ignored in --skip-name-resolve mode.
2019-12-06 12:44:26 0 [Note] Reading of all Master_info entries succeeded
2019-12-06 12:44:26 0 [Note] Added new Master_info '' to hash table
2019-12-06 12:44:26 0 [Note] /opt/bitnami/mariadb/sbin/mysqld: ready for connections.
Version: '10.3.20-MariaDB'  socket: '/opt/bitnami/mariadb/tmp/mysql.sock'  port: 3306  Source distribution
```

Logs of `moodle`
```
Welcome to the Bitnami moodle container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-moodle
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-moodle/issues

WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
nami    INFO  Initializing apache
nami    INFO  apache successfully initialized
nami    INFO  Initializing php
nami    INFO  php successfully initialized
nami    INFO  Initializing mysql-client
nami    INFO  mysql-client successfully initialized
nami    INFO  Initializing moodle
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at mariadb:3306
mysql-c INFO  MySQL server listening and working at mariadb:3306
moodle  INFO  Running Moodle install. Please be patient...
Error executing 'postInstallation': EEXIST: file already exists, symlink '/bitnami/moodle' -> '/opt/bitnami/moodle'
```

The only thing I've changed in the docker-compose.yml is that I added the environment variable `http_proxy` because of office policies.

**Comment by reschandreas** [comment]
I added the flag `NAMI_DEBUG=--log-level=trace` in the docker-compose.yml for more output

```
app-entrypoint.sh 13:17:51.53 
app-entrypoint.sh 13:17:51.53 Welcome to the Bitnami moodle container
app-entrypoint.sh 13:17:51.53 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-moodle
app-entrypoint.sh 13:17:51.53 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-moodle/issues
app-entrypoint.sh 13:17:51.54 
app-entrypoint.sh 13:17:51.54 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
nami    INFO  Initializing apache
nami    INFO  apache successfully initialized
nami    INFO  Initializing php
php     TRACE [configurePermissions] List of files: ["/opt/bitnami/php/tmp"]
php     TRACE [configurePermissions] File to chown: /opt/bitnami/php/tmp
php     TRACE [configurePermissions] List of files: ["/opt/bitnami/php/logs"]
php     TRACE [configurePermissions] File to chown: /opt/bitnami/php/logs
php     TRACE [configurePermissions] List of files: ["/opt/bitnami/php/var","/opt/bitnami/php/var/log","/opt/bitnami/php/var/run"]
php     TRACE [configurePermissions] File to chown: /opt/bitnami/php/var
php     TRACE [configurePermissions] File to chown: /opt/bitnami/php/var/log
php     TRACE [configurePermissions] File to chown: /opt/bitnami/php/var/run
nami    INFO  php successfully initialized
nami    INFO  Initializing mysql-client
nami    INFO  mysql-client successfully initialized
nami    INFO  Initializing moodle
moodle  DEBUG Preparing apache environment...
apache  TRACE Skipping reload: com.bitnami.apache not running
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at mariadb:3306
mysql-c TRACE [canConnect] Testing connection with 'bn_moodle' user
mysql-c TRACE [showDatabases] Getting databases for 'bn_moodle' user
mysql-c TRACE [execute] Executing: mysql -N -P 3306 -hmariadb -ubn_moodle -e SHOW DATABASES;
mysql-c TRACE [execute] Result: {"code":0,"stdout":"bitnami_moodle\ninformation_schema\ntest\n","stderr":""}
mysql-c TRACE [showDatabases] Databases: bitnami_moodle
information_schema
test

mysql-c TRACE [canConnect] Connection with 'bn_moodle' user is successful
mysql-c INFO  MySQL server listening and working at mariadb:3306
moodle  INFO  Running Moodle install. Please be patient...
php     TRACE [runProgram] Executing: /opt/bitnami/php/bin/php admin/cli/install.php,--lang=en,--chmod=2775,--wwwroot=http://localhost:80,--dataroot=/bitnami/moodle/moodledata,--dbtype=mariadb,--dbhost=mariadb,--dbport=3306,--dbname=bitnami_moodle,--dbuser=bn_moodle,--dbpass=,--adminuser=user,--adminpass=bitnami,--adminemail=user@example.com,--fullname="New Site",--shortname="New Site",--non-interactive,--allow-unstable,--agree-license
mysql-c TRACE [execute] Executing: mysql -N -P 3306 -hmariadb -Dbitnami_moodle -ubn_moodle -e INSERT INTO mdl_config (id, name, value) VALUES (NULL, 'noreplyaddress', 'noreply@moodle');
mysql-c TRACE [execute] Result: {"code":0,"stdout":"","stderr":""}
mysql-c TRACE [execute] Executing: mysql -N -P 3306 -hmariadb -Dbitnami_moodle -ubn_moodle -e UPDATE mdl_user SET email='user@example.com';
mysql-c TRACE [execute] Result: {"code":0,"stdout":"","stderr":""}
mysql-c TRACE [execute] Executing: mysql -N -P 3306 -hmariadb -Dbitnami_moodle -ubn_moodle -e UPDATE mdl_course SET summary='Moodle powered by Bitnami';
mysql-c TRACE [execute] Result: {"code":0,"stdout":"","stderr":""}
moodle  TRACE [prepareDataToPersist] Preparing /opt/bitnami/moodle to persist in /bitnami/moodle
Error executing 'postInstallation': EEXIST: file already exists, symlink '/bitnami/moodle' -> '/opt/bitnami/moodle'
nami    TRACE Error: Error executing 'postInstallation': EEXIST: file already exists, symlink '/bitnami/moodle' -> '/opt/bitnami/moodle'
    at Object.fs.symlinkSync (fs.js:1014:18)
    at Object.link (/opt/bitnami/nami/node_modules/nami-utils/lib/file/link.js:34:8)
    at Object.<anonymous> (/opt/bitnami/nami/node_modules/lodash/index.js:51:276)
    at _.each (/root/.nami/components/com.bitnami.moodle/lib/volume.js:132:13)
    at r (/opt/bitnami/nami/node_modules/lodash/index.js:5:348)
    at Function.sf (/opt/bitnami/nami/node_modules/lodash/index.js:78:256)
    at Function.<anonymous> (/opt/bitnami/nami/node_modules/lodash/index.js:51:276)
    at Object.prepareDataToPersist (/root/.nami/components/com.bitnami.moodle/lib/volume.js:121:7)
    at Component.$app.postInstallation (/root/.nami/components/com.bitnami.moodle/main.js:39:21)
    at Component.runStep (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:159:12)
```

**Comment by sameersbn** [comment]
I just setup a centos 7 virtualbox machine and applied all the updates before installing docker using instructions from https://docs.docker.com/install/linux/docker-ce/centos/  and used the following to test it out:

```bash
curl -LO https://raw.githubusercontent.com/bitnami/bitnami-docker-moodle/master/docker-compose.yml
docker-compose up
```

I did not encounter the issue you reported and everything went well. 
Can you retry after deleting all the docker images used in this stack?

Below are the os and docker details 

```bash
$ cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

```bash
$ docker version
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:25:41 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:24:18 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

```bash
$ docker info
Client:
 Debug Mode: false

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 2
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-1062.7.1.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 3.7GiB
 Name: localhost.localdomain
 ID: XKWG:4UMU:N7ZB:KRIC:CZOO:UW2C:3HGU:BWKB:CYO3:Y3GS:W4KV:6ZQP
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

**Comment by reschandreas** [comment]
I managed to brick my virtual machine. I then set up a new VM and low and behold it worked on the first try. The storage driver is now `overlay2`, everything else is literally the same.
I guess that was the problem.

**Comment by carrodher** [comment]
I'm glad the problem was solved and thanks for sharing with the community the solution! Please, feel free to reopen the issue if the problem appears again.
