### ISSUE TITLE
Upgrade stuck

### ISSUE THREAD

**Issue by GCBenlloch** [bitnami/bitnami-docker-moodle#133]
**Description**

I followed the steps to upgrade from 3.4.2 to 3.9.1 and when starting the container it gets stuck at upgrading database and restarts itself.

`aula_virtual_1                | moodle 14:12:54.38 Welcome to the Bitnami moodle container
aula_virtual_1                | moodle 14:12:54.38 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-moodle
aula_virtual_1                | moodle 14:12:54.38 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-moodle/issues
aula_virtual_1                | moodle 14:12:54.38
aula_virtual_1                | moodle 14:12:54.39 INFO  ==> ** Starting Moodle setup **
aula_virtual_1                | moodle 14:12:54.42 INFO  ==> Configuring PHP options
aula_virtual_1                | moodle 14:12:54.44 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
aula_virtual_1                | moodle 14:12:54.49 INFO  ==> Restoring persisted Moodle installation
aula_virtual_1                | moodle 14:12:54.50 INFO  ==> Trying to connect to the database server
aula_virtual_1                | moodle 14:12:54.54 INFO  ==> Running database upgrade`

**Comment by GCBenlloch** [comment]
`
mysql-c TRACE [canConnect] Connection with 'root' user is successful
aula_virtual_1                | mysql-c INFO  MySQL server listening and working at db:3306
aula_virtual_1                | moodle  DEBUG Preparing apache environment...
aula_virtual_1                | apache  TRACE Skipping reload: com.bitnami.apache not running
aula_virtual_1                | php     TRACE [runProgram] Executing: /opt/bitnami/php/bin/php admin/cli/install.php,--lang=en,--chmod=2775,--wwwroot=http://localhost:80,--dataroot=/bitnami/moodle/moodledata,--dbtype=mariadb,--dbhost=db,--dbport=3306,--dbname=*******,--dbuser=******,--dbpass=*****,--adminuser=*****,--adminpass=*****,--adminemail=******,--fullname="New Site",--shortname="New Site",--non-interactive,--allow-unstable,--agree-license
aula_virtual_1                | Error executing 'postInstallation': Program exited with exit code 1
aula_virtual_1                | nami    TRACE Error: Error executing 'postInstallation': Program exited with exit code 1
aula_virtual_1                |     at runProgram (/opt/bitnami/nami/node_modules/nami-utils/lib/os/run-program.js:223:14)
aula_virtual_1                |     at Object.runProgram (/opt/bitnami/nami/node_modules/nami-utils/lib/os/index.js:63:12)
aula_virtual_1                |     at Object.$app.helpers.execute (/root/.nami/components/com.bitnami.php/helpers.js:73:14)
aula_virtual_1                |     at Object.<anonymous> (/opt/bitnami/nami/node_modules/lodash/index.js:33:285)
aula_virtual_1                |     at Object.$app.helpers.runMoodleInstall (/root/.nami/components/com.bitnami.moodle/helpers.js:88:7)
aula_virtual_1                |     at Component.$app.postInstallation (/root/.nami/components/com.bitnami.moodle/main.js:25:18)
aula_virtual_1                |     at Component.runStep (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:159:12)
aula_virtual_1                |     at _.each.step (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:236:32)
aula_virtual_1                |     at ot (/opt/bitnami/nami/node_modules/lodash/index.js:12:507)
aula_virtual_1                |     at Function.<anonymous> (/opt/bitnami/nami/node_modules/lodash/index.js:33:421)

`
